from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('MASTER_ADMIN', 'Master Admin'), ('BRAND_OWNER', 'Brand Owner'), ('STORE_ADMIN', 'Store Admin'), ('RECEPTIONIST', 'Receptionist'), ('THERAPIST', 'Therapist'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('loyalty_points', models.PositiveIntegerField(default=0)),
                ('expo_push_token', models.CharField(blank=True, help_text='Expo push token for mobile notifications', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('duration_days', models.IntegerField(default=30)),
                ('max_redemptions', models.IntegerField(default=1)),
                ('redemption_count', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('issued_by', models.CharField(blank=True, help_text='Internal user ID or name', max_length=255, null=True)),
                ('source_tag', models.CharField(help_text='Channel that produced stores that stayed', max_length=100)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'access_code',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(blank=True, help_text='For walk-ins without an account', max_length=255, null=True)),
                ('guest_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(choices=[('WALK_IN', 'Walk In'), ('ONLINE', 'Online'), ('PHONE', 'Phone')], default='WALK_IN', max_length=20)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('IN_PROGRESS', 'In Progress'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show'), ('RESCHEDULE_REQUESTED', 'Reschedule Requested')], default='BOOKED', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_pattern', models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=20, null=True)),
                ('recurrence_end_date', models.DateField(blank=True, null=True)),
                ('is_group', models.BooleanField(default=False)),
                ('group_size', models.PositiveIntegerField(default=1)),
                ('is_home_service', models.BooleanField(default=False)),
                ('service_address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('actor_type', models.CharField(help_text="'internal_user' | 'system'", max_length=50)),
                ('action', models.CharField(help_text='create, update, delete, status change', max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=255)),
                ('before', models.JSONField(blank=True, help_text='State before change', null=True)),
                ('after', models.JSONField(blank=True, help_text='State after change', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand_logos/')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('SALON', 'Salon'), ('SPA', 'Spa'), ('BEAUTY_CLINIC', 'Beauty Clinic'), ('MASSAGE_CENTER', 'Massage Center'), ('BARBER_SHOP', 'Barber Shop'), ('NAIL_STUDIO', 'Nail Studio'), ('TATTOO_STUDIO', 'Tattoo Studio'), ('MAKEUP_ARTIST', 'Makeup Artist'), ('HOME_BEAUTY_SERVICES', 'Home Beauty Services'), ('WELLNESS_CENTRE', 'Wellness Centre'), ('BEAUTY_ACADEMY', 'Beauty Academy'), ('SKIN_CLINIC', 'Skin Clinic'), ('HAIR_CLINIC', 'Hair Clinic'), ('COSMETIC_CLINIC', 'Cosmetic Clinic'), ('LASER_CLINIC', 'Laser Clinic'), ('AYURVEDA_CENTRE', 'Ayurveda Centre'), ('PHYSIOTHERAPY_CENTRE', 'Physiotherapy Centre'), ('YOGA_STUDIO', 'Yoga Studio'), ('FITNESS_STUDIO', 'Fitness Studio'), ('NUTRITION_CENTRE', 'Nutrition Centre'), ('MEDICAL_SPA', 'Medical Spa')], default='SALON', max_length=30)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('address', models.TextField()),
                ('country', models.CharField(default='India', max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CanonicalService',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('default_duration_min', models.IntegerField(default=60)),
                ('buffer_before_min', models.IntegerField(default=0)),
                ('buffer_after_min', models.IntegerField(default=0)),
                ('resource_type', models.CharField(choices=[('none', 'None'), ('chair', 'Chair'), ('room', 'Room'), ('equipment', 'Equipment')], default='none', help_text='Unified resource logic: chair = room = equipment', max_length=20)),
                ('gender_applicability', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex')], default='unisex', max_length=20)),
                ('skill_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'canonical_service',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'db_table': 'city',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerMergeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surviving_customer_id', models.UUIDField()),
                ('merged_customer_id', models.UUIDField()),
                ('merged_by', models.CharField(help_text='Restricted to superadmin and ops roles', max_length=255)),
                ('affected_records', models.JSONField(default=dict, help_text='Full record of store links, bookings, reviews moved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reverted_at', models.DateTimeField(blank=True, help_text='Reversible within 30 days', null=True)),
            ],
            options={
                'db_table': 'customer_merge_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlobalCustomer',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_e164', models.CharField(blank=True, db_index=True, help_text='Normalized E.164 phone identity key. Can be null for walk-ins.', max_length=20, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('deletion_requested', 'DPDP Deletion Requested'), ('deleted', 'Deleted / Anonymized')], default='active', max_length=30)),
                ('is_global', models.BooleanField(default=True, help_text='FALSE for walk-ins with no phone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImpersonationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_user_id', models.CharField(max_length=255)),
                ('store_group_id', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('read_only', 'Read Only'), ('write', 'Write')], default='read_only', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(help_text='Required especially for write mode')),
            ],
            options={
                'db_table': 'impersonation_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalUser',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('ops', 'Operations'), ('reviewer', 'Reviewer')], default='reviewer', max_length=20)),
                ('totp_secret', models.CharField(blank=True, help_text='Base32 TOTP secret for mandatory 2FA', max_length=100, null=True)),
                ('is_totp_enabled', models.BooleanField(default=False, help_text='True once user verifies first 6-digit TOTP code')),
                ('last_login_at', models.DateTimeField(blank=True, help_text='Last recorded activity timestamp for 60m inactivity timeout', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'internal_user',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated revenue for Nearbyme', max_digits=10)),
                ('gateway_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated payment processing fee', max_digits=10)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=20)),
                ('requires_manager_approval', models.BooleanField(default=False)),
                ('is_discount_approved', models.BooleanField(default=False)),
                ('is_review_reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='core.appointment')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address_line', models.TextField()),
                ('pincode', models.CharField(max_length=20)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outlets', to='core.city')),
            ],
            options={
                'db_table': 'outlet',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price_paise', models.BigIntegerField(default=0, help_text='Price in integer paise (29900 = ₹299.00)')),
                ('billing_period', models.CharField(default='monthly', max_length=50)),
                ('outlet_limit', models.IntegerField(default=1)),
                ('professional_limit', models.IntegerField(default=5)),
                ('feature_flags', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'plan',
                'ordering': ['price_paise'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='NearbyMe', max_length=255)),
                ('support_email', models.EmailField(default='support@nearbyme.in', max_length=254)),
                ('support_phone', models.CharField(default='+91 00000 00000', max_length=20)),
                ('default_currency', models.CharField(default='INR', max_length=10)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('platform_commission_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='Platform cut from marketplace bookings', max_digits=5)),
                ('gateway_fee_percentage', models.DecimalField(decimal_places=2, default=2.0, help_text='Payment processing fee', max_digits=5)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        migrations.CreateModel(
            name='PlatformSubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, help_text='Commission taken on online bookings', max_digits=5)),
                ('features', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(help_text='Barcode / Stock Keeping Unit', max_length=100, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('low_stock_warning', models.IntegerField(default=5)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('outlet', models.ForeignKey(blank=True, help_text='Specific branch outlet for this inventory item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.outlet')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(blank=True, help_text='Branch outlet receiving this stock delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='core.outlet')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_home_service_available', models.BooleanField(default=False)),
                ('is_premium_listing', models.BooleanField(default=False, help_text='Bumps service in marketplace search for a fee')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategoryPhase1',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('applies_to', models.CharField(choices=[('salon', 'Salon'), ('spa', 'Spa'), ('both', 'Both')], default='both', max_length=20)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'category',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, help_text='lat,long e.g. 12.9716,77.5946', max_length=255, null=True)),
                ('working_hours', models.JSONField(default=dict, help_text='e.g. {"mon": "09:00-21:00", "tue": "09:00-21:00", "sun": "closed"}')),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('is_premium_listing', models.BooleanField(default=False, help_text='Bumps store in marketplace search for a fee')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='core.brand')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='core.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreGroup',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_phone', models.CharField(max_length=20)),
                ('owner_email', models.EmailField(max_length=254)),
                ('gstin', models.CharField(blank=True, help_text='Validated 15-character GSTIN', max_length=15, null=True)),
                ('pan', models.CharField(blank=True, max_length=10, null=True)),
                ('business_type', models.CharField(choices=[('spa', 'Spa'), ('salon', 'Salon'), ('both', 'Both')], default='salon', max_length=10)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('active', 'Active'), ('suspended', 'Suspended'), ('dormant', 'Dormant'), ('offboarded', 'Offboarded')], default='applied', max_length=20)),
                ('status_changed_at', models.DateTimeField(auto_now=True)),
                ('term_start', models.DateTimeField(blank=True, null=True)),
                ('term_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('access_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_groups', to='core.accesscode')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_groups', to='core.plan')),
            ],
            options={
                'db_table': 'store_group',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreService',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('default_price_paise', models.BigIntegerField(help_text='Price stored strictly in integer paise')),
                ('duration_min', models.IntegerField()),
                ('is_active_in_store', models.BooleanField(default=True, help_text='Defaults TRUE immediately so store can bill same minute')),
                ('marketplace_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('merged', 'Merged into Canonical'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, null=True)),
                ('canonical_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_variants', to='core.canonicalservice')),
                ('store_group', models.ForeignKey(help_text='Belongs to GROUP, not one outlet', on_delete=django.db.models.deletion.CASCADE, related_name='store_services', to='core.storegroup')),
            ],
            options={
                'db_table': 'store_service',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20)),
                ('max_stores', models.PositiveIntegerField(default=1)),
                ('max_staff', models.PositiveIntegerField(default=5)),
                ('max_customers', models.PositiveIntegerField(default=500)),
                ('features', models.JSONField(default=list, help_text='List of feature strings e.g. ["AI Analytics", "SMS Marketing"]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='TrainingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField()),
                ('category', models.CharField(blank=True, help_text='e.g., Technical, Soft Skills, Product Training', max_length=100, null=True)),
                ('is_premium', models.BooleanField(default=False, help_text='Requires payment to access')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='core.city')),
            ],
            options={
                'db_table': 'zone',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit (Add Funds)'), ('DEBIT', 'Debit (Spend Funds)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateField()),
                ('preferred_time_slot', models.CharField(help_text='e.g. Morning, Afternoon, or specific time', max_length=100)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('NOTIFIED', 'Notified'), ('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlists', to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(blank=True, help_text='Branch outlet waitlist', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlists', to='core.outlet')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlists', to='core.store')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(blank=True, help_text='Specific branch outlet for this vendor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='core.outlet')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='core.store')),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='core.invoice')),
                ('therapist', models.ForeignKey(limit_choices_to={'role': 'THERAPIST'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TherapistSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_notifications', models.BooleanField(default=True)),
                ('sms_alerts', models.BooleanField(default=True)),
                ('biometric_login', models.BooleanField(default=False)),
                ('dark_mode', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TherapistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('specializations', models.CharField(blank=True, help_text='e.g., Hair Coloring, Bridal Makeup', max_length=255, null=True)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('certificates', models.JSONField(blank=True, default=list, help_text='List of certificate names/urls')),
                ('awards', models.JSONField(blank=True, default=list, help_text='List of awards')),
                ('languages', models.JSONField(blank=True, default=list, help_text='List of spoken languages')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('CANCELED', 'Canceled'), ('FREE_TRIAL', 'Free Trial')], default='FREE_TRIAL', max_length=50)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.platformsubscriptionplan')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_subscription', to='core.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=50)),
                ('to_status', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('changed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_by_type', models.CharField(choices=[('internal_user', 'Internal User'), ('system', 'System')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='core.storegroup')),
            ],
            options={
                'verbose_name_plural': 'store status histories',
                'db_table': 'store_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='core.store')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('to_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='core.store')),
            ],
        ),
        migrations.CreateModel(
            name='StaffTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=50)),
                ('certification_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(limit_choices_to={'role__in': ['RECEPTIONIST', 'THERAPIST', 'STORE_ADMIN']}, on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_trainings', to='core.store')),
            ],
        ),
        migrations.CreateModel(
            name='StaffTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Monthly Bonus, Top Performer', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_paid_out', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(blank=True, help_text='Branch outlet this incentive belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incentives', to='core.outlet')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to='core.store')),
            ],
        ),
        migrations.CreateModel(
            name='StaffDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_url', models.URLField()),
                ('document_type', models.CharField(choices=[('ID', 'ID Proof'), ('CERTIFICATE', 'Certificate'), ('CONTRACT', 'Contract')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_staff_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('outlet', models.ForeignKey(blank=True, help_text='Specific branch outlet for this shift', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='core.outlet')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='core.store')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_used', to='core.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Discounted bundle price', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('services', models.ManyToManyField(related_name='packages', to='core.service')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='core.store')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_categories', to='core.business')),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.servicecategory'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('outlet', models.ForeignKey(blank=True, help_text='Specific branch outlet this treatment room belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='core.outlet')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.store')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Rating from 1 to 5')),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Moderation'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reply_text', models.TextField(blank=True, help_text='Staff or store reply to the review', null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.store')),
                ('therapist', models.ForeignKey(blank=True, help_text='Staff member this review is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_points_awarded', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.purchaseorder')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='core.store'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vendor'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.store'),
        ),
        migrations.CreateModel(
            name='PlatformInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('PAID', 'Paid'), ('VOID', 'Void'), ('UNCOLLECTIBLE', 'Uncollectible')], default='OPEN', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_invoices', to='core.store')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Credit/Debit Card'), ('UPI', 'UPI'), ('WALLET', 'Wallet'), ('GIFT_CARD', 'Gift Card'), ('PACKAGE', 'Package Redemption')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='outlet',
            name='store_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to='core.storegroup'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outlets', to='core.zone'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, help_text='e.g. APPOINTMENT, TIP, SYSTEM', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tier_type', models.CharField(choices=[('STANDARD', 'Standard'), ('VIP', 'VIP'), ('CORPORATE', 'Corporate'), ('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], default='STANDARD', max_length=50)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage off on all services', max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, help_text='Cost to buy this membership', max_digits=10)),
                ('duration_days', models.PositiveIntegerField(default=365)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_tiers', to='core.store')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('message_body', models.TextField()),
                ('target_audience', models.CharField(help_text='e.g., ALL_CUSTOMERS, INACTIVE_CUSTOMERS', max_length=100)),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('outlet', models.ForeignKey(blank=True, help_text='Branch outlet executing this campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='core.outlet')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='core.store')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('outlet', models.ForeignKey(blank=True, help_text='Branch outlet of the requesting staff', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests', to='core.outlet')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='core.store')),
            ],
        ),
        migrations.CreateModel(
            name='KycDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('gst_cert', 'GST Certificate'), ('pan', 'PAN Card'), ('trade_licence', 'Trade Licence'), ('bank_proof', 'Bank Proof'), ('business_cert', 'Business Incorporation Certificate')], max_length=20)),
                ('file_url', models.URLField(blank=True, help_text='Signed URL for cloud storage', max_length=500, null=True)),
                ('file', models.FileField(blank=True, help_text='Uploaded document file', null=True, upload_to='kyc_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, help_text='Internal user reviewer', max_length=255, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Required on rejection', null=True)),
                ('store_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to='core.storegroup')),
            ],
            options={
                'db_table': 'kyc_document',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.invoice')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='outlet',
            field=models.ForeignKey(blank=True, help_text='Branch outlet that issued this POS receipt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.outlet'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.store'),
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('initial_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchaser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_gift_cards', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_cards', to='core.store')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('RENT', 'Rent'), ('UTILITIES', 'Utilities'), ('SALARY', 'Salary'), ('MARKETING', 'Marketing'), ('SUPPLIES', 'Supplies'), ('PETTY_CASH', 'Petty Cash'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_incurred', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(blank=True, help_text='Branch outlet that incurred this expense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.outlet')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.store')),
            ],
        ),
        migrations.CreateModel(
            name='DailyRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cash_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_card_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('outlet', models.ForeignKey(blank=True, help_text='Branch outlet for this daily cash register', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_registers', to='core.outlet')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_registers', to='core.store')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_timing', models.CharField(blank=True, choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening')], max_length=50, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('anniversary', models.DateField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('skin_type', models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('DRY', 'Dry'), ('OILY', 'Oily'), ('COMBINATION', 'Combination'), ('SENSITIVE', 'Sensitive')], max_length=20, null=True)),
                ('hair_type', models.CharField(blank=True, choices=[('STRAIGHT', 'Straight'), ('WAVY', 'Wavy'), ('CURLY', 'Curly'), ('COILY', 'Coily')], max_length=20, null=True)),
                ('medical_notes', models.TextField(blank=True, null=True)),
                ('churn_risk_score', models.IntegerField(default=0, help_text='AI calculated score 0-100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicepackage')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_received', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_written', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_frozen', models.BooleanField(default=False)),
                ('frozen_until', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.membershiptier')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_type', models.CharField(choices=[('marketing_whatsapp', 'Marketing WhatsApp'), ('marketing_sms', 'Marketing SMS'), ('marketing_email', 'Marketing Email'), ('photos', 'Photo Permission')], max_length=30)),
                ('granted', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, help_text='Revocations recorded with timestamp, never deleted', null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='core.globalcustomer')),
            ],
            options={
                'db_table': 'customer_consent',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FLAT', 'Flat Amount')], default='PERCENTAGE', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maximum_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Cap on max discount for percentage coupons', max_digits=10, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('usage_limit', models.PositiveIntegerField(default=1)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='core.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid_out', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.invoiceitem')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='core.store')),
                ('therapist', models.ForeignKey(limit_choices_to={'role': 'THERAPIST'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='canonicalservice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_services', to='core.servicecategoryphase1'),
        ),
        migrations.CreateModel(
            name='BusinessSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('TRIAL', 'Trial')], default='TRIAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.business')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.subscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='core.business'),
        ),
        migrations.CreateModel(
            name='BeforeAfterGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_photo_url', models.URLField(blank=True, null=True)),
                ('after_photo_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformation_galleries', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankSettlementAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(help_text='Store securely — encrypt at rest in production', max_length=50)),
                ('ifsc_code', models.CharField(help_text='11-character RBI IFSC code', max_length=11)),
                ('bank_name', models.CharField(max_length=255)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_type', models.CharField(choices=[('current', 'Current Account'), ('savings', 'Savings Account')], default='current', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.CharField(blank=True, help_text='Store owner who submitted', max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Set True by Master Admin after manual verification')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('activated_by', models.CharField(blank=True, help_text='Internal user who activated payouts', max_length=255, null=True)),
                ('weekly_payout_enabled', models.BooleanField(default=False, help_text='Enables automated weekly revenue disbursements')),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('store_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_settlement_account', to='core.storegroup')),
            ],
            options={
                'db_table': 'bank_settlement_account',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day')], default='PRESENT', max_length=20)),
                ('outlet', models.ForeignKey(blank=True, help_text='Specific branch outlet where attendance was marked', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='core.outlet')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.store')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Locked price at time of booking', max_digits=10)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.appointment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.service')),
                ('therapist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='outlet',
            field=models.ForeignKey(blank=True, help_text='Specific branch outlet where this appointment takes place', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='core.outlet'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.room'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.store'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(blank=True, help_text='If null, visible to all stores', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.store')),
            ],
        ),
        migrations.CreateModel(
            name='AccessCodeRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('term_start', models.DateTimeField()),
                ('term_end', models.DateTimeField()),
                ('access_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemption_logs', to='core.accesscode')),
                ('store_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_redemption_logs', to='core.storegroup')),
            ],
            options={
                'db_table': 'access_code_redemption',
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.AddField(
            model_name='accesscode',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_codes', to='core.plan'),
        ),
        migrations.AddField(
            model_name='user',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.brand'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='outlet',
            field=models.ForeignKey(blank=True, help_text='Specific branch outlet this user/staff is assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='core.outlet'),
        ),
        migrations.AddField(
            model_name='user',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.store'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='StoreServiceOutletOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_paise', models.BigIntegerField(help_text='Price stored strictly in integer paise')),
                ('duration_min', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_overrides', to='core.outlet')),
                ('store_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_overrides', to='core.storeservice')),
            ],
            options={
                'db_table': 'store_service_outlet_override',
                'unique_together': {('store_service', 'outlet')},
            },
        ),
        migrations.CreateModel(
            name='StaffTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(help_text='MM-YYYY', max_length=7)),
                ('revenue_target', models.DecimalField(decimal_places=2, max_digits=10)),
                ('achieved_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_targets', to='core.store')),
            ],
            options={
                'unique_together': {('staff', 'month_year')},
            },
        ),
        migrations.CreateModel(
            name='StaffAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(help_text='0=Monday, 6=Sunday')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Staff Availabilities',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('staff', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(help_text='MM-YYYY', max_length=7)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commissions_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('incentives', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(blank=True, help_text='Branch outlet for this staff payroll', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls', to='core.outlet')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='core.store')),
            ],
            options={
                'unique_together': {('staff', 'month_year')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteTherapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_therapists', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('customer', 'therapist')},
            },
        ),
        migrations.CreateModel(
            name='CustomerStoreLink',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_visit_at', models.DateTimeField(blank=True, null=True)),
                ('last_visit_at', models.DateTimeField(blank=True, null=True)),
                ('visit_count', models.IntegerField(default=0)),
                ('lifetime_spend_paise', models.BigIntegerField(default=0, help_text='Total spend stored strictly in integer paise')),
                ('preferred_professional_id', models.CharField(blank=True, help_text="Always use 'professional', never staff/employee/therapist", max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Per-store notes require a documented support reason to view in Master Admin', null=True)),
                ('tags', models.JSONField(default=list)),
                ('lifecycle_stage', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('repeat', 'Repeat'), ('lapsing', 'Lapsing'), ('churned', 'Churned'), ('reactivated', 'Reactivated')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(help_text='All per-store data lives here, never on customer', on_delete=django.db.models.deletion.CASCADE, related_name='store_links', to='core.globalcustomer')),
                ('store_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_links', to='core.storegroup')),
            ],
            options={
                'db_table': 'customer_store_link',
                'ordering': ['-last_visit_at', '-created_at'],
                'unique_together': {('customer', 'store_group')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('name', 'business')},
        ),
    ]
