# Generated by Django 4.2.30 on 2026-08-13 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
                ('display_role', models.CharField(blank=True, help_text="Free text, e.g. 'Senior Stylist'", max_length=100, null=True)),
                ('phone_e164', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('link_status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('removed', 'Removed')], default='invited', max_length=20)),
                ('is_bookable', models.BooleanField(default=True)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professionals', to='core.outlet')),
                ('store_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professionals', to='core.storegroup')),
                ('user_account', models.ForeignKey(blank=True, help_text='Nullable until the invited professional accepts', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'professional',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('chair', 'Chair'), ('room', 'Room'), ('equipment', 'Equipment')], max_length=20)),
                ('capacity', models.IntegerField(default=1, help_text='Usually 1; a couples room = 2')),
                ('is_bookable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.outlet')),
            ],
            options={
                'db_table': 'resource',
                'ordering': ['outlet', 'resource_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalTimeOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, help_text='Internal user ID or name', max_length=255, null=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off_blocks', to='core.professional')),
            ],
            options={
                'db_table': 'professional_time_off',
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='Null means open-ended', null=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_shifts', to='core.outlet')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='core.professional')),
            ],
            options={
                'db_table': 'professional_shift',
                'ordering': ['professional', 'weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_tag', models.CharField(help_text='Maps to CanonicalService.skill_tag', max_length=100)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.professional')),
            ],
            options={
                'db_table': 'professional_skill',
                'ordering': ['skill_tag'],
                'unique_together': {('professional', 'skill_tag')},
            },
        ),
    ]
