# Generated by Django 4.2.30 on 2026-08-13 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_professional_resource_professionaltimeoff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('amount_paise', models.BigIntegerField(help_text='Correction amount stored strictly in integer paise')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='core.invoice')),
            ],
            options={
                'db_table': 'credit_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applies_to', models.CharField(choices=[('service', 'Service'), ('product', 'Product'), ('category', 'Category')], max_length=20)),
                ('rate_type', models.CharField(choices=[('percent', 'Percent'), ('flat', 'Flat')], max_length=20)),
                ('rate_value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g. 12.50) if rate_type=percent, else flat amount in rupees', max_digits=10)),
                ('effective_from', models.DateField()),
                ('professional', models.ForeignKey(blank=True, help_text='Null applies to every professional', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='core.professional')),
                ('store_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='core.storegroup')),
            ],
            options={
                'db_table': 'commission_rule',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='CommissionAccrual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_paise', models.BigIntegerField(help_text='Line amount commission was calculated on, in integer paise')),
                ('commission_paise', models.BigIntegerField(help_text='Computed commission amount, in integer paise')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_accruals', to='core.invoiceitem')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_accruals', to='core.professional')),
            ],
            options={
                'db_table': 'commission_accrual',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('walk_in', 'Walk In'), ('front_desk', 'Front Desk'), ('phone', 'Phone'), ('online', 'Online'), ('whatsapp', 'WhatsApp')], default='walk_in', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_service', 'In Service'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='draft', max_length=20)),
                ('booking_start', models.DateTimeField()),
                ('booking_end', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('booked_by', models.ForeignKey(blank=True, help_text='Staff member who created this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_made', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.globalcustomer')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.outlet')),
            ],
            options={
                'db_table': 'booking',
                'ordering': ['-booking_start'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot_start', models.DateTimeField()),
                ('slot_end', models.DateTimeField()),
                ('price_paise', models.BigIntegerField(help_text='Price stored strictly in integer paise, locked at time of booking')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('started', 'Started'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('was_overridden', models.BooleanField(default=False, help_text='True if this slot was booked despite a conflict warning')),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.booking')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_overrides', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_slots', to='core.professional')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_slots', to='core.resource')),
                ('store_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_slots', to='core.storeservice')),
            ],
            options={
                'db_table': 'appointment_slot',
                'ordering': ['slot_start'],
            },
        ),
    ]
