# Generated by Django 4.2.30 on 2026-08-13 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_creditnote_commissionrule_commissionaccrual_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='finalised_at',
            field=models.DateTimeField(blank=True, help_text='Null means still a draft. Once set, the invoice is immutable.', null=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='invoice_prefix',
            field=models.CharField(blank=True, help_text="Short code used as the prefix for this outlet's invoice numbers, e.g. 'BLR1'. Auto-derived from the name if left blank.", max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Credit/Debit Card'), ('UPI', 'UPI'), ('WALLET', 'Wallet'), ('GIFT_CARD', 'Gift Card'), ('PACKAGE', 'Package Redemption'), ('MEMBERSHIP_CREDIT', 'Membership Credit'), ('PACKAGE_CREDIT', 'Package Credit')], max_length=20),
        ),
    ]
