# Generated by Django 4.2.30 on 2026-08-13 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_invoice_created_by_invoice_finalised_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='professional',
            field=models.ForeignKey(blank=True, help_text='Who performed this line, for commission accrual', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='core.professional'),
        ),
    ]
