# Generated by Django 4.2.30 on 2026-08-13 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_invoiceitem_professional'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.booking'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='global_customer',
            field=models.ForeignKey(blank=True, help_text='Phase1 customer identity, for invoices raised from a Booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.globalcustomer'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='store_service',
            field=models.ForeignKey(blank=True, help_text='Phase1 service catalog reference, for lines sourced from a Booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='core.storeservice'),
        ),
    ]
