# Generated by Django 4.2.30 on 2026-08-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_invoice_booking_invoice_global_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='invoice_prefix',
            field=models.CharField(blank=True, help_text="Short code used as the prefix for this outlet's invoice numbers, e.g. 'BLR1'. Auto-derived from the name if left blank.", max_length=10, null=True, unique=True),
        ),
    ]
