# Generated by Django 4.2.30 on 2026-08-13 08:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_outlet_invoice_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagePlan',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('service_credits', models.JSONField(default=dict, help_text='{store_service_id: credit_count} bundled into this package')),
                ('validity_days', models.IntegerField(default=180)),
                ('price_paise', models.BigIntegerField(help_text='What the customer pays, in integer paise')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_plans', to='core.storegroup')),
            ],
            options={
                'db_table': 'package_plan',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('service_credits', models.JSONField(default=dict, help_text='{store_service_id: credits_remaining}')),
                ('valid_until', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='core.globalcustomer')),
                ('store_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='core.storegroup')),
            ],
            options={
                'db_table': 'package',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('value_paise', models.BigIntegerField(help_text='Wallet credit granted on purchase, in integer paise')),
                ('validity_days', models.IntegerField(default=365)),
                ('price_paise', models.BigIntegerField(help_text='What the customer pays, in integer paise')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_plans', to='core.storegroup')),
            ],
            options={
                'db_table': 'membership_plan',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=200)),
                ('value_paise_remaining', models.BigIntegerField()),
                ('valid_until', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.globalcustomer')),
                ('store_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.storegroup')),
            ],
            options={
                'db_table': 'membership',
                'ordering': ['-created_at'],
            },
        ),
    ]
