# Generated by Django 4.2.30 on 2026-08-13 08:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_packageplan_package_membershipplan_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproduct',
            name='store_service',
            field=models.ForeignKey(blank=True, help_text='Phase1 service catalog reference, for services sourced from a Booking', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_used', to='core.storeservice'),
        ),
        migrations.AlterField(
            model_name='serviceproduct',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_used', to='core.service'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_deducted', models.IntegerField(help_text='Positive integer; always a deduction from stock_quantity')),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='core.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='core.product')),
            ],
            options={
                'db_table': 'stock_movement',
                'ordering': ['-created_at'],
            },
        ),
    ]
