# Generated by Django 4.2.30 on 2026-08-13 08:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_serviceproduct_store_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], max_length=20)),
                ('target_type', models.CharField(choices=[('lapsed_60d', 'Not visited in 60+ days'), ('birthday_this_week', 'Birthday this week'), ('lifecycle_lapsing', 'Lifecycle stage: Lapsing')], max_length=30)),
                ('message_template', models.TextField(help_text="Use {name} as a placeholder for the customer's name")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('store_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='core.storegroup')),
            ],
            options={
                'db_table': 'campaign',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignSend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, help_text='Set by a future delivery-webhook integration; unused until a real gateway is connected', null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='core.campaign')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_sends', to='core.globalcustomer')),
            ],
            options={
                'db_table': 'campaign_send',
                'ordering': ['-sent_at'],
                'unique_together': {('campaign', 'customer')},
            },
        ),
    ]
