# Generated by Django 4.2.30 on 2026-08-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_campaign_campaignsend'),
    ]

    operations = [
        migrations.AddField(
            model_name='canonicalservice',
            name='hsn_sac_code',
            field=models.CharField(blank=True, help_text="GST HSN/SAC code for this service, e.g. '999721'", max_length=20, null=True),
        ),
    ]
