# Generated by Django 4.2.30 on 2026-08-13 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_canonicalservice_hsn_sac_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='outlet',
            field=models.ForeignKey(blank=True, help_text='Bridge to the Phase1 Outlet this legacy Store maps to, for online booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_stores', to='core.outlet'),
        ),
    ]
