# Generated by Django 4.2.30 on 2026-08-14 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_store_outlet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_e164', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('profile_photo_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'professional_account',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5')),
                ('professional_rating', models.PositiveSmallIntegerField(blank=True, help_text='Rating from 1 to 5, only when a professional is tagged', null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('moderation_status', models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden')], default='visible', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_reviews', to='core.booking')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_reviews_given', to='core.globalcustomer')),
                ('professional_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_received', to='core.professionalaccount')),
                ('store_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_reviews', to='core.storegroup')),
            ],
            options={
                'db_table': 'professional_review',
                'ordering': ['-created_at'],
                'unique_together': {('booking', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='ReviewResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professional_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_responses', to='core.professionalaccount')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='core.professionalreview')),
            ],
            options={
                'db_table': 'review_response',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReputationConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('portability_granted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_consent', to='core.professionalaccount')),
            ],
            options={
                'db_table': 'reputation_consent',
            },
        ),
        migrations.CreateModel(
            name='ReputationAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_services', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reputation', to='core.professionalaccount')),
            ],
            options={
                'db_table': 'reputation_aggregate',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalTip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paise', models.BigIntegerField(help_text='Tip amount stored strictly in integer paise')),
                ('method', models.CharField(choices=[('upi_deeplink', 'UPI Deep Link'), ('vpa_direct', 'VPA Direct')], max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('unconfirmed', 'Unconfirmed')], default='initiated', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_tips', to='core.appointmentslot')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_tips', to='core.booking')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_tips_given', to='core.globalcustomer')),
                ('professional_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips_received', to='core.professionalaccount')),
            ],
            options={
                'db_table': 'professional_tip',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalPortfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('professional_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='core.professionalaccount')),
            ],
            options={
                'db_table': 'professional_portfolio',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalCertification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('issuer', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('professional_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='core.professionalaccount')),
            ],
            options={
                'db_table': 'professional_certification',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='PayoutDestination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('upi_vpa', 'UPI VPA'), ('bank', 'Bank Account')], max_length=20)),
                ('vpa', models.CharField(blank=True, help_text='UPI VPA, e.g. name@bank', max_length=255, null=True)),
                ('bank_account_masked', models.CharField(blank=True, help_text='Masked account number, e.g. XXXX1234', max_length=50, null=True)),
                ('holder_name', models.CharField(max_length=255)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='unverified', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professional_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_destinations', to='core.professionalaccount')),
            ],
            options={
                'db_table': 'payout_destination',
                'ordering': ['-created_at'],
            },
        ),
        # user_account used to be a bigint FK to User; it is now a uuid FK to
        # ProfessionalAccount. Postgres has no bigint->uuid cast, and every
        # existing row has this column NULL, so drop and recreate instead of
        # altering the column type in place.
        migrations.RemoveField(
            model_name='professional',
            name='user_account',
        ),
        migrations.AddField(
            model_name='professional',
            name='user_account',
            field=models.ForeignKey(blank=True, help_text="Nullable until the invited professional accepts. Points to the professional's global identity, not their store-login User.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_profiles', to='core.professionalaccount'),
        ),
    ]
