# Generated by Django 4.2.30 on 2026-08-14 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_professionalaccount_professionalreview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalaccount',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Null until the professional accepts their invite and creates a login', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
