# Generated by Django 4.2.30 on 2026-07-16 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_appointment_group_size_appointment_is_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='core.store'),
        ),
    ]
