# Generated by Django 4.2.30 on 2026-08-16 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_conversation_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('revenue_share_percent', models.DecimalField(decimal_places=2, default=0, help_text="Platform's cut of premiums sold through this partnership", max_digits=5)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='PENDING', max_length=10)),
                ('contract_start', models.DateField(blank=True, null=True)),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'insurance_partner',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=150, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('price_paise', models.BigIntegerField(help_text='Price in integer paise')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'marketplace_product',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('instructor_name', models.CharField(blank=True, max_length=150, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('price_paise', models.BigIntegerField(help_text='Price in integer paise')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'training_course',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='platformsubscriptionplan',
            name='includes_ai_assistant',
            field=models.BooleanField(default=False, help_text='AI assistant add-on bundled into this plan'),
        ),
        migrations.AddField(
            model_name='platformsubscriptionplan',
            name='includes_analytics',
            field=models.BooleanField(default=False, help_text='Analytics add-on bundled into this plan'),
        ),
        migrations.AddField(
            model_name='platformsubscriptionplan',
            name='includes_crm',
            field=models.BooleanField(default=False, help_text='CRM add-on bundled into this plan'),
        ),
        migrations.AlterField(
            model_name='platformsubscriptionplan',
            name='features',
            field=models.JSONField(blank=True, default=dict, help_text='Any other feature flags not covered by the fields above'),
        ),
        migrations.CreateModel(
            name='PlatformCommissionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount_paise', models.BigIntegerField(help_text='Booking total the commission was calculated on, in integer paise')),
                ('commission_percent_applied', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_paise', models.BigIntegerField(help_text="Platform's commission on this booking, in integer paise")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_ledger_entries', to='core.booking')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_ledger_entries', to='core.store')),
            ],
            options={
                'db_table': 'platform_commission_ledger',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('STRIPE', 'Stripe'), ('PAYU', 'PayU'), ('OTHER', 'Other')], max_length=20)),
                ('period_month', models.CharField(help_text='MM-YYYY', max_length=7)),
                ('gross_volume_paise', models.BigIntegerField(help_text='Total payment volume processed, in integer paise')),
                ('gateway_fee_paise', models.BigIntegerField(help_text='Fee charged by the gateway, in integer paise')),
                ('net_revenue_paise', models.BigIntegerField(default=0, help_text="Platform's markup/net revenue on the gateway fee, in integer paise")),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(blank=True, help_text='Blank for platform-wide gateway revenue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_revenue_entries', to='core.store')),
            ],
            options={
                'db_table': 'payment_gateway_revenue',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('placement', models.CharField(choices=[('HOME_BANNER', 'Home Banner'), ('SEARCH_TOP', 'Search Top Result'), ('CATEGORY_FEATURED', 'Category Featured')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ENDED', 'Ended')], default='DRAFT', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget_paise', models.BigIntegerField(help_text='Amount the store paid for this campaign, in integer paise')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to='core.store')),
            ],
            options={
                'db_table': 'ad_campaign',
                'ordering': ['-created_at'],
            },
        ),
    ]
