# Generated by Django 4.2.30 on 2026-08-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_insurancepartner_marketplaceproduct_trainingcourse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_home_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
