# Generated by Django 4.2.30 on 2026-07-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_appointment_status_therapistsettings_stafftask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expo_push_token',
            field=models.CharField(blank=True, help_text='Expo push token for mobile notifications', max_length=255, null=True),
        ),
    ]
