# Generated by Django 4.2.30 on 2026-08-19 04:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_phoneotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot_start', models.DateTimeField()),
                ('slot_end', models.DateTimeField()),
                ('session_token', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('held', 'Held'), ('converted', 'Converted'), ('expired', 'Expired'), ('released', 'Released')], default='held', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_holds', to='core.globalcustomer')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_holds', to='core.outlet')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_holds', to='core.professional')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_holds', to='core.resource')),
                ('store_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_holds', to='core.storeservice')),
            ],
            options={
                'db_table': 'slot_hold',
                'ordering': ['-created_at'],
            },
        ),
    ]
