# Generated by Django 4.2.30 on 2026-07-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_platformsubscriptionplan_storesubscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('SALON', 'Salon'), ('SPA', 'Spa'), ('BEAUTY_CLINIC', 'Beauty Clinic'), ('MASSAGE_CENTER', 'Massage Center'), ('BARBER_SHOP', 'Barber Shop'), ('NAIL_STUDIO', 'Nail Studio'), ('TATTOO_STUDIO', 'Tattoo Studio'), ('MAKEUP_ARTIST', 'Makeup Artist'), ('HOME_BEAUTY_SERVICES', 'Home Beauty Services'), ('WELLNESS_CENTRE', 'Wellness Centre'), ('BEAUTY_ACADEMY', 'Beauty Academy'), ('SKIN_CLINIC', 'Skin Clinic'), ('HAIR_CLINIC', 'Hair Clinic'), ('COSMETIC_CLINIC', 'Cosmetic Clinic'), ('LASER_CLINIC', 'Laser Clinic'), ('AYURVEDA_CENTRE', 'Ayurveda Centre'), ('PHYSIOTHERAPY_CENTRE', 'Physiotherapy Centre'), ('YOGA_STUDIO', 'Yoga Studio'), ('FITNESS_STUDIO', 'Fitness Studio'), ('NUTRITION_CENTRE', 'Nutrition Centre'), ('MEDICAL_SPA', 'Medical Spa')], default='SALON', max_length=30),
        ),
    ]
