# Generated by Django 4.2.30 on 2026-08-19 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_slothold'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePublicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Public microsite path, e.g. /s/<slug>', max_length=80, unique=True)),
                ('custom_domain', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('headline', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('cover_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('gallery', models.JSONField(blank=True, default=list, help_text='List of image URLs')),
                ('amenities', models.JSONField(blank=True, default=list, help_text="List of short strings, e.g. ['Parking', 'AC', 'Wifi']")),
                ('cancellation_policy_text', models.TextField(blank=True, null=True)),
                ('is_microsite_live', models.BooleanField(default=True, help_text='Every approved store gets a microsite immediately')),
                ('marketplace_public', models.BooleanField(default=False, help_text="This store's own opt-in to cross-store discovery — still gated by the city's dark-launch flag")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_profile', to='core.store')),
            ],
            options={
                'db_table': 'store_public_profile',
            },
        ),
        migrations.CreateModel(
            name='CityMarketplaceFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('min_store_threshold', models.PositiveIntegerField(default=10, help_text='Suggested minimum approved stores before flipping this on')),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_flag', to='core.city')),
            ],
        ),
    ]
