# Generated by Django 4.2.30 on 2026-08-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_onlinepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsubscriptionplan',
            name='includes_premium_listing',
            field=models.BooleanField(default=False, help_text='Sponsored/boosted placement in customer search bundled into this plan'),
        ),
    ]
