# Generated by Django 4.2.30 on 2026-08-19 06:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_platformsubscriptionplan_includes_premium_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(blank=True, help_text='For walk-ins without an account', max_length=255, null=True)),
                ('guest_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('in_service', 'In Service'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='waiting', max_length=20)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries', to='core.globalcustomer')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='core.outlet')),
                ('professional', models.ForeignKey(blank=True, help_text='Preferred professional, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries', to='core.professional')),
                ('store_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries', to='core.storeservice')),
            ],
            options={
                'db_table': 'queue_entry',
                'ordering': ['checked_in_at'],
            },
        ),
    ]
