# Generated by Django 4.2.30 on 2026-08-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_queueentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='on_the_way_at',
            field=models.DateTimeField(blank=True, help_text='Home-service only — set when the professional marks themselves en route', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='therapist_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='therapist_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
