# Generated by Django 4.2.30 on 2026-08-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_booking_location_updated_at_booking_on_the_way_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessSubscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
