# Generated by Django 4.2.30 on 2026-08-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_delete_businesssubscription_delete_subscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepayment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When the gateway signature was verified and status became CAPTURED', null=True),
        ),
    ]
