# Generated by Django 4.2.30 on 2026-08-20 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_onlinepayment_confirmed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFavourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_stores', to='core.globalcustomer')),
                ('professional_account', models.ForeignKey(blank=True, help_text='Optional: a specific professional at this store the customer prefers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favourited_at', to='core.professionalaccount')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='core.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'store')},
            },
        ),
    ]
