# Generated by Django 4.2.30 on 2026-08-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_customerfavourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepayment',
            name='payment_type',
            field=models.CharField(choices=[('full', 'Full payment'), ('deposit', 'Deposit')], default='full', max_length=10),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='total_amount_paise',
            field=models.BigIntegerField(default=0, help_text='Full service price. Equals amount_paise for a full payment; balance_due = total_amount_paise - amount_paise for a deposit'),
        ),
        migrations.AddField(
            model_name='storeservice',
            name='deposit_percentage',
            field=models.PositiveSmallIntegerField(default=20, help_text='What percentage of the price a customer can pay online as a deposit, balance due at venue'),
        ),
        migrations.AlterField(
            model_name='onlinepayment',
            name='amount_paise',
            field=models.BigIntegerField(help_text='Amount actually charged via the gateway — the deposit amount when payment_type=deposit'),
        ),
    ]
