# Generated by Django 4.2.30 on 2026-08-20 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_onlinepayment_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutdestination',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payoutdestination',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalreview',
            name='media_url',
            field=models.URLField(blank=True, help_text='Optional photo/video attached to the review', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='professionaltip',
            name='payment_ref',
            field=models.CharField(blank=True, help_text='UPI transaction ref / provider reference, if captured', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professionaltip',
            name='store_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_tips', to='core.storegroup'),
        ),
        migrations.AlterField(
            model_name='professionalreview',
            name='moderation_status',
            field=models.CharField(choices=[('visible', 'Visible'), ('flagged', 'Flagged'), ('hidden', 'Hidden')], default='visible', max_length=20),
        ),
    ]
