# Generated by Django 4.2.30 on 2026-08-21 04:02

from django.db import migrations, models


def backfill_booking_codes(apps, schema_editor):
    Booking = apps.get_model('core', 'Booking')
    for seq, booking in enumerate(Booking.objects.order_by('created_at'), start=1):
        Booking.objects.filter(pk=booking.pk).update(booking_code=f"BKG-{seq:06d}")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_invoice_paise_conversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(blank=True, editable=False, help_text='Human-readable reference, e.g. BKG-000123. Auto-assigned on first save.', max_length=20, null=True, unique=True),
        ),
        migrations.RunPython(backfill_booking_codes, noop_reverse),
    ]
